In [48]:
#import sweetviz

import pandas as pd
import os
import sweetviz as sv
%matplotlib inline

In [85]:
filename = '2020-07-12_14-06-14_f49f0704_TESTLOOP_RawData.xlsx'
foldername = 'Raw Data Vishal'

path = os.path.join(foldername,filename)
path

df = pd.read_excel(path,header=None)

In [78]:
df.shape
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Columns: 4099 entries, 0 to 4098
dtypes: float64(4097), object(2)
memory usage: 10.3+ MB

,2,3,4,5,6,7,8,9,10,11,...,4089,4090,4091,4092,4093,4094,4095,4096,4097,4098
count,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,...,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000,330.000000
mean,1.279688,-0.098390,-0.257718,-0.367614,-0.381818,-0.368466,-0.382860,-0.370975,-0.378741,-0.373295,...,-0.373958,-0.375426,-0.374763,-0.373201,-0.373958,-0.373011,-0.372633,-0.373059,-0.375331,-0.374953
std,0.000000,0.074008,0.276957,0.432704,0.452652,0.431439,0.451027,0.439359,0.450335,0.439281,...,0.447686,0.447394,0.447318,0.446729,0.447255,0.446375,0.445244,0.445485,0.444846,0.446573
min,1.279688,-0.171875,-0.640625,-1.093750,-1.140625,-1.093750,-1.109375,-1.078125,-1.109375,-1.140625,...,-1.140625,-1.125000,-1.078125,-1.062500,-1.062500,-1.078125,-1.062500,-1.078125,-1.093750,-1.078125
25%,1.279688,-0.171875,-0.640625,-0.968750,-1.015625,-0.968750,-1.015625,-0.984375,-1.015625,-0.984375,...,-1.000000,-1.000000,-1.000000,-1.000000,-0.996094,-0.984375,-0.984375,-0.984375,-1.000000,-1.000000
50%,1.279688,-0.125000,-0.140625,-0.125000,-0.140625,-0.125000,-0.140625,-0.125000,-0.125000,-0.125000,...,-0.125000,-0.125000,-0.125000,-0.125000,-0.125000,-0.125000,-0.125000,-0.125000,-0.125000,-0.125000
75%,1.279688,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.279688,0.015625,0.046875,0.046875,0.015625,0.015625,0.015625,0.046875,0.046875,0.031250,...,0.062500,0.125000,0.140625,0.140625,0.093750,0.078125,0.062500,0.062500,0.046875,0.093750

In [79]:
df.col

Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            4089, 4090, 4091, 4092, 4093, 4094, 4095, 4096, 4097, 4098],
           dtype='int64', length=4099)

In [87]:
df.shape
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 330 entries, 0 to 329
Columns: 4099 entries, 0 to 4098
dtypes: float64(4097), object(2)
memory usage: 10.3+ MB

,0,1,2,3,4,5,6,7,8,9,...,4089,4090,4091,4092,4093,4094,4095,4096,4097,4098
0,07-09-2020 12:16:13,xAccelTime,1.279688,-0.171875,-0.640625,-0.96875,-0.921875,-0.96875,-1.015625,-0.984375,...,-1.140625,-1.125000,-1.062500,-1.046875,-1.06250,-1.015625,-1.000000,-0.984375,-1.000000,-0.984375
1,07-09-2020 12:51:53,xAccelTime,1.279688,-0.171875,-0.640625,-1.09375,-1.046875,-1.00000,-0.953125,-0.984375,...,-0.953125,-0.968750,-1.015625,-1.015625,-1.03125,-1.015625,-0.968750,-0.953125,-0.890625,-0.953125
2,07-09-2020 14:40:46,xAccelTime,1.279688,-0.171875,-0.640625,-0.96875,-1.015625,-0.96875,-1.015625,-0.984375,...,-1.015625,-1.000000,-1.000000,-1.000000,-1.00000,-1.000000,-1.015625,-1.000000,-1.000000,-1.000000
3,07-09-2020 15:19:00,xAccelTime,1.279688,-0.171875,-0.640625,-0.96875,-1.015625,-0.96875,-1.015625,-1.046875,...,-1.015625,-1.015625,-1.000000,-0.984375,-1.00000,-1.000000,-1.000000,-1.000000,-0.984375,-0.984375
4,07-09-2020 15:57:47,xAccelTime,1.279688,-0.171875,-0.640625,-0.96875,-1.015625,-0.96875,-1.015625,-0.984375,...,-1.000000,-1.000000,-1.000000,-1.015625,-1.03125,-1.015625,-1.000000,-1.000000,-1.000000,-1.000000

In [101]:
df.iloc[0:1,3:].isnull()

3       1
4       1
5       1
6       1
7       1
       ..
4095    1
4096    1
4097    1
4098    1
Mean    1
Length: 4097, dtype: int64

In [92]:
df['Mean'] = df.iloc[:,3:].mean()

In [93]:
df['Mean']

0           NaN
1           NaN
2           NaN
3     -0.098390
4     -0.257718
         ...
325   -0.375095
326   -0.375663
327   -0.374858
328   -0.374574
329   -0.375331
Name: Mean, Length: 330, dtype: float64